VERSION = "1.9.2"
UPDATE_INFO_URL = "https://raw.githubusercontent.com/LeviCrypto99/lts/main/version.json"
UPDATE_TIMEOUT_SEC = 5
UPDATE_AUTH_TOKEN_ENV = "LTS_UPDATE_TOKEN"
UPDATER_URL = ""
ALLOW_LAUNCH_ON_UPDATE_CHECK_FAILURE = True
UPDATE_CHECK_STRICT_MODE_ENV = "LTS_UPDATE_STRICT_MODE"
